# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - fanuc_arm_controller

  fanuc_arm_controller:
    type: FollowJointTrajectory
    # When using gz_ros2_control, the action is at:
    # /fanuc_arm_controller/follow_joint_trajectory
    action_ns: follow_joint_trajectory
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6